package org.dogej.models.util;

import com.fasterxml.jackson.annotation.JsonProperty;

public class ValidateAddress {
    private boolean isValid;
    private String address;
    private String scriptPubKey;
    private boolean isScript;
    private boolean isWitness;
    private Long witnessVersion;
    private String witnessProgram;
    private boolean isMine;//NB absent in bitcoin
    private boolean isWatchonly;//NB absent in bitcoin
    private String hdKeyPath;//NB absent in bitcoin
    private String hdMasterKeyId;//NB absent in bitcoin
    private String pubKey;//NB absent in bitcoin
    private boolean isCompressed;//NB absent in bitcoin
    private String account;//NB absent in bitcoin
    private Long timestamp;//NB absent in bitcoin

    /**
     * If the address is valid or not. If not, this is the only property returned.
     */
    @JsonProperty("isvalid") public boolean isValid() {
        return isValid;
    }

    @JsonProperty public String getAddress() {
        return address;
    }

    /**
     * The hex-encoded scriptPubKey generated by the address
     */
    @JsonProperty public String getScriptPubKey() {
        return scriptPubKey;
    }

    @JsonProperty("isscript") public boolean isScript() {
        return isScript;
    }

    @JsonProperty("iswitness") public boolean isWitness() {
        return isWitness;
    }

    /**
     * (optional) The version number of the witness program
     */
    @JsonProperty("witness_version") public Long getWitnessVersion() {
        return witnessVersion;
    }

    /**
     * (optional) The hex value of the witness program
     */
    @JsonProperty("witness_program") public String getWitnessProgram() {
        return witnessProgram;
    }

    @JsonProperty("iswatchonly") public boolean isWatchonly() {
        return isWatchonly;
    }

    @JsonProperty("ismine") public boolean isMine() {
        return isMine;
    }

    @JsonProperty("hdkeypath") public String getHdKeyPath() {
        return hdKeyPath;
    }

    @JsonProperty("hdmasterkeyid") public String getHdMasterKeyId() {
        return hdMasterKeyId;
    }

    @JsonProperty("pubkey") public String getPubKey() {
        return pubKey;
    }

    @JsonProperty("iscompressed") public boolean isCompressed() {
        return isCompressed;
    }

    public void setCompressed(boolean compressed) {
        isCompressed = compressed;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public Long getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
    }

    public void setValid(boolean valid) {
        isValid = valid;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setScriptPubKey(String scriptPubKey) {
        this.scriptPubKey = scriptPubKey;
    }

    public void setScript(boolean script) {
        isScript = script;
    }

    public void setWitness(boolean witness) {
        isWitness = witness;
    }

    public void setWitnessVersion(Long witnessVersion) {
        this.witnessVersion = witnessVersion;
    }

    public void setWitnessProgram(String witnessProgram) {
        this.witnessProgram = witnessProgram;
    }

    public void setMine(boolean mine) {
        isMine = mine;
    }

    public void setWatchonly(boolean watchonly) {
        isWatchonly = watchonly;
    }

    public void setHdKeyPath(String hdKeyPath) {
        this.hdKeyPath = hdKeyPath;
    }

    public void setHdMasterKeyId(String hdMasterKeyId) {
        this.hdMasterKeyId = hdMasterKeyId;
    }

    public void setPubKey(String pubKey) {
        this.pubKey = pubKey;
    }

    @Override
    public String toString() {
        return "ValidateAddress{" +
                "isValid=" + isValid +
                ", address='" + address + '\'' +
                ", scriptPubKey='" + scriptPubKey + '\'' +
                ", isScript=" + isScript +
                ", isWitness=" + isWitness +
                ", witnessVersion=" + witnessVersion +
                ", witnessProgram='" + witnessProgram + '\'' +
                ", isMine=" + isMine +
                ", isWatchonly=" + isWatchonly +
                ", hdKeyPath='" + hdKeyPath + '\'' +
                ", hdMasterKeyId='" + hdMasterKeyId + '\'' +
                ", pubKey='" + pubKey + '\'' +
                ", isCompressed=" + isCompressed +
                ", account='" + account + '\'' +
                ", timestamp=" + timestamp +
                '}';
    }
}
